### ISSUE TITLE
Implement malloc_mutex debugging facilities

### ISSUE THREAD

**Issue by jasone** [jemalloc/jemalloc#358]
Implement at least the following capabilities into ```malloc_mutex_t``` (if ```--enable-debug``` is specified):

- Assert that caller owns mutex.
- Associate ranks with mutexes, and dynamically verify that locking order reversals do not occur.

This will allow assertions to serve as documentation of locking protocols, as well as actually increasing confidence in the implementation.

**Comment by jasone** [comment]
a15841cc7d7c60b2c72c091d8048223789f5c4e0 fixes a compilation error caused by b2c0d6322d2307458ae2b28545f8a5c9903d7ef5.
