### ISSUE TITLE
error: unknown type name 'pszind_t'

### ISSUE THREAD

**Issue by barracuda156** [jemalloc/jemalloc#2271]
`jemalloc` fails to build on 10.6 PPC with `gcc11`:

```
include/jemalloc/internal/sz.h:66:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   66 |         pszind_t mod = ((((psz-1) & delta_inverse_mask) >> lg_delta)) &
      |         ^~~~~~~~
      |         szind_t
include/jemalloc/internal/sz.h:57:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   57 |         pszind_t x = lg_floor((psz<<1)-1);
      |         ^~~~~~~~
      |         szind_t
include/jemalloc/internal/sz.h:69:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   69 |         pszind_t ind = grp + mod;
      |         ^~~~~~~~
      |         szind_t
include/jemalloc/internal/sz.h: At top level:
include/jemalloc/internal/sz.h:74:20: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   74 | sz_pind2sz_compute(pszind_t pind) {
      |                    ^~~~~~~~
      |                    szind_t
include/jemalloc/internal/sz.h:58:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   58 |         pszind_t shift = (x < SC_LG_NGROUP + LG_PAGE) ?
      |         ^~~~~~~~
      |         szind_t
include/jemalloc/internal/sz.h:94:19: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   94 | sz_pind2sz_lookup(pszind_t pind) {
      |                   ^~~~~~~~
      |                   szind_t
include/jemalloc/internal/sz.h:60:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   60 |         pszind_t grp = shift << SC_LG_NGROUP;
      |         ^~~~~~~~
      |         szind_t
In file included from include/jemalloc/internal/jemalloc_internal_includes.h:66,
                 from src/jemalloc.c:3:
include/jemalloc/internal/extent_externs.h:35:49: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   35 | size_t extents_nextents_get(extents_t *extents, pszind_t ind);
      |                                                 ^~~~~~~~
      |                                                 szind_t
include/jemalloc/internal/sz.h:101:12: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
  101 | sz_pind2sz(pszind_t pind) {
      |            ^~~~~~~~
      |            szind_t
In file included from include/jemalloc/internal/arena_types.h:4,
                 from include/jemalloc/internal/jemalloc_internal_includes.h:45,
                 from src/background_thread.c:3:
include/jemalloc/internal/sz.h: In function 'sz_size2index_compute':
include/jemalloc/internal/sc.h:185:19: warning: "LG_QUANTUM" is not defined, evaluates to 0 [-Wundef]
  185 | #define SC_NTINY (LG_QUANTUM - SC_LG_TINY_MIN)
      |                   ^~~~~~~~~~
include/jemalloc/internal/sz.h:129:6: note: in expansion of macro 'SC_NTINY'
  129 | #if (SC_NTINY != 0)
      |      ^~~~~~~~
include/jemalloc/internal/extent_externs.h:37:47: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   37 | size_t extents_nbytes_get(extents_t *extents, pszind_t ind);
      |                                               ^~~~~~~~
      |                                               szind_t
include/jemalloc/internal/sz.h: In function 'sz_index2size_compute':
include/jemalloc/internal/sc.h:185:19: warning: "LG_QUANTUM" is not defined, evaluates to 0 [-Wundef]
  185 | #define SC_NTINY (LG_QUANTUM - SC_LG_TINY_MIN)
      |                   ^~~~~~~~~~
include/jemalloc/internal/sz.h:173:6: note: in expansion of macro 'SC_NTINY'
  173 | #if (SC_NTINY > 0)
      |      ^~~~~~~~
include/jemalloc/internal/sz.h: In function 'sz_s2u_compute':
include/jemalloc/internal/sc.h:185:19: warning: "LG_QUANTUM" is not defined, evaluates to 0 [-Wundef]
  185 | #define SC_NTINY (LG_QUANTUM - SC_LG_TINY_MIN)
      |                   ^~~~~~~~~~
include/jemalloc/internal/sz.h:219:6: note: in expansion of macro 'SC_NTINY'
  219 | #if (SC_NTINY > 0)
      |      ^~~~~~~~
include/jemalloc/internal/sz.h:62:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   62 |         pszind_t lg_delta = (x < SC_LG_NGROUP + LG_PAGE + 1) ?
      |         ^~~~~~~~
      |         szind_t
include/jemalloc/internal/sz.h:66:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   66 |         pszind_t mod = ((((psz-1) & delta_inverse_mask) >> lg_delta)) &
      |         ^~~~~~~~
      |         szind_t
include/jemalloc/internal/sz.h:69:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   69 |         pszind_t ind = grp + mod;
      |         ^~~~~~~~
      |         szind_t
In file included from include/jemalloc/internal/extent_inlines.h:10,
                 from include/jemalloc/internal/jemalloc_internal_includes.h:86,
                 from src/jemalloc.c:3:
include/jemalloc/internal/sz.h:52:24: error: unknown type name 'pszind_t'
   52 | JEMALLOC_ALWAYS_INLINE pszind_t
      |                        ^~~~~~~~
include/jemalloc/internal/sz.h: In function 'sz_psz2ind':
include/jemalloc/internal/sz.h:57:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   57 |         pszind_t x = lg_floor((psz<<1)-1);
      |         ^~~~~~~~
      |         szind_t
include/jemalloc/internal/sz.h: At top level:
include/jemalloc/internal/sz.h:74:20: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   74 | sz_pind2sz_compute(pszind_t pind) {
      |                    ^~~~~~~~
      |                    szind_t
include/jemalloc/internal/sz.h:58:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   58 |         pszind_t shift = (x < SC_LG_NGROUP + LG_PAGE) ?
      |         ^~~~~~~~
      |         szind_t
include/jemalloc/internal/sz.h:94:19: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   94 | sz_pind2sz_lookup(pszind_t pind) {
      |                   ^~~~~~~~
      |                   szind_t
include/jemalloc/internal/sz.h:60:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   60 |         pszind_t grp = shift << SC_LG_NGROUP;
      |         ^~~~~~~~
      |         szind_t
include/jemalloc/internal/sz.h:101:12: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
  101 | sz_pind2sz(pszind_t pind) {
      |            ^~~~~~~~
      |            szind_t
include/jemalloc/internal/sz.h:62:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   62 |         pszind_t lg_delta = (x < SC_LG_NGROUP + LG_PAGE + 1) ?
      |         ^~~~~~~~
      |         szind_t
In file included from include/jemalloc/internal/arena_types.h:4,
                 from include/jemalloc/internal/jemalloc_internal_includes.h:45,
                 from src/base.c:3:
include/jemalloc/internal/sz.h: In function 'sz_size2index_compute':
include/jemalloc/internal/sc.h:185:19: warning: "LG_QUANTUM" is not defined, evaluates to 0 [-Wundef]
  185 | #define SC_NTINY (LG_QUANTUM - SC_LG_TINY_MIN)
      |                   ^~~~~~~~~~
include/jemalloc/internal/sz.h:129:6: note: in expansion of macro 'SC_NTINY'
  129 | #if (SC_NTINY != 0)
      |      ^~~~~~~~
include/jemalloc/internal/sz.h: In function 'sz_index2size_compute':
include/jemalloc/internal/sc.h:185:19: warning: "LG_QUANTUM" is not defined, evaluates to 0 [-Wundef]
  185 | #define SC_NTINY (LG_QUANTUM - SC_LG_TINY_MIN)
      |                   ^~~~~~~~~~
include/jemalloc/internal/sz.h:173:6: note: in expansion of macro 'SC_NTINY'
  173 | #if (SC_NTINY > 0)
      |      ^~~~~~~~
include/jemalloc/internal/sz.h:66:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   66 |         pszind_t mod = ((((psz-1) & delta_inverse_mask) >> lg_delta)) &
      |         ^~~~~~~~
      |         szind_t
include/jemalloc/internal/sz.h: In function 'sz_s2u_compute':
include/jemalloc/internal/sc.h:185:19: warning: "LG_QUANTUM" is not defined, evaluates to 0 [-Wundef]
  185 | #define SC_NTINY (LG_QUANTUM - SC_LG_TINY_MIN)
      |                   ^~~~~~~~~~
include/jemalloc/internal/sz.h:219:6: note: in expansion of macro 'SC_NTINY'
  219 | #if (SC_NTINY > 0)
      |      ^~~~~~~~
include/jemalloc/internal/sz.h:69:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   69 |         pszind_t ind = grp + mod;
      |         ^~~~~~~~
      |         szind_t
include/jemalloc/internal/sz.h: At top level:
include/jemalloc/internal/sz.h:74:20: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   74 | sz_pind2sz_compute(pszind_t pind) {
      |                    ^~~~~~~~
      |                    szind_t
include/jemalloc/internal/sz.h:94:19: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
   94 | sz_pind2sz_lookup(pszind_t pind) {
      |                   ^~~~~~~~
      |                   szind_t
include/jemalloc/internal/sz.h:101:12: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
  101 | sz_pind2sz(pszind_t pind) {
      |            ^~~~~~~~
      |            szind_t
In file included from include/jemalloc/internal/arena_types.h:4,
                 from include/jemalloc/internal/jemalloc_internal_includes.h:45,
                 from src/jemalloc.c:3:
include/jemalloc/internal/sz.h: In function 'sz_size2index_compute':
include/jemalloc/internal/sc.h:185:19: warning: "LG_QUANTUM" is not defined, evaluates to 0 [-Wundef]
  185 | #define SC_NTINY (LG_QUANTUM - SC_LG_TINY_MIN)
      |                   ^~~~~~~~~~
include/jemalloc/internal/sz.h:129:6: note: in expansion of macro 'SC_NTINY'
  129 | #if (SC_NTINY != 0)
      |      ^~~~~~~~
include/jemalloc/internal/sz.h: In function 'sz_index2size_compute':
include/jemalloc/internal/sc.h:185:19: warning: "LG_QUANTUM" is not defined, evaluates to 0 [-Wundef]
  185 | #define SC_NTINY (LG_QUANTUM - SC_LG_TINY_MIN)
      |                   ^~~~~~~~~~
include/jemalloc/internal/sz.h:173:6: note: in expansion of macro 'SC_NTINY'
  173 | #if (SC_NTINY > 0)
      |      ^~~~~~~~
include/jemalloc/internal/sz.h: In function 'sz_s2u_compute':
include/jemalloc/internal/sc.h:185:19: warning: "LG_QUANTUM" is not defined, evaluates to 0 [-Wundef]
  185 | #define SC_NTINY (LG_QUANTUM - SC_LG_TINY_MIN)
      |                   ^~~~~~~~~~
include/jemalloc/internal/sz.h:219:6: note: in expansion of macro 'SC_NTINY'
  219 | #if (SC_NTINY > 0)
      |      ^~~~~~~~
src/arena.c: In function 'arena_stats_merge':
src/arena.c:173:14: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
  173 |         for (pszind_t i = 0; i < SC_NPSIZES; i++) {
      |              ^~~~~~~~
      |              szind_t
src/arena.c:176:25: warning: implicit declaration of function 'extents_nextents_get'; did you mean 'extents_npages_get'? [-Wimplicit-function-declaration]
  176 |                 dirty = extents_nextents_get(&arena->extents_dirty, i);
      |                         ^~~~~~~~~~~~~~~~~~~~
      |                         extents_npages_get
src/arena.c:179:31: warning: implicit declaration of function 'extents_nbytes_get'; did you mean 'extents_npages_get'? [-Wimplicit-function-declaration]
  179 |                 dirty_bytes = extents_nbytes_get(&arena->extents_dirty, i);
      |                               ^~~~~~~~~~~~~~~~~~
      |                               extents_npages_get
src/arena.c: In function 'arena_slab_regind':
src/arena.c:338:43: warning: parameter 'binind' set but not used [-Wunused-but-set-parameter]
  338 | arena_slab_regind(extent_t *slab, szind_t binind, const void *ptr) {
      |                                   ~~~~~~~~^~~~~~
src/arena.c: In function 'arena_large_malloc_stats_update':
src/arena.c:385:24: warning: variable 'hindex' set but not used [-Wunused-but-set-variable]
  385 |         szind_t index, hindex;
      |                        ^~~~~~
src/arena.c: In function 'arena_large_dalloc_stats_update':
src/arena.c:401:24: warning: variable 'hindex' set but not used [-Wunused-but-set-variable]
  401 |         szind_t index, hindex;
      |                        ^~~~~~
src/arena.c: In function 'arena_bin_choose_lock':
src/arena.c:1365:61: warning: parameter 'binind' set but not used [-Wunused-but-set-parameter]
 1365 | arena_bin_choose_lock(tsdn_t *tsdn, arena_t *arena, szind_t binind,
      |                                                     ~~~~~~~~^~~~~~
src/base.c: In function 'base_extent_bump_alloc_post':
src/base.c:205:25: warning: variable 'index_floor' set but not used [-Wunused-but-set-variable]
  205 |                 szind_t index_floor =
      |                         ^~~~~~~~~~~
src/base.c: At top level:
src/base.c:249:19: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
  249 |     unsigned ind, pszind_t *pind_last, size_t *extent_sn_next, size_t size,
      |                   ^~~~~~~~
      |                   szind_t
src/arena.c: In function 'arena_dissociate_bin_slab':
src/arena.c:1627:25: warning: variable 'binind' set but not used [-Wunused-but-set-variable]
 1627 |                 szind_t binind = extent_szind_get(slab);
      |                         ^~~~~~
make: *** [src/background_thread.sym.o] Error 1
make: *** Waiting for unfinished jobs....
src/arena.c: In function 'arena_dalloc_bin_locked_impl':
src/arena.c:1687:13: warning: parameter 'binind' set but not used [-Wunused-but-set-parameter]
 1687 |     szind_t binind, extent_t *slab, void *ptr, bool junked) {
      |     ~~~~~~~~^~~~~~
src/arena.c: In function 'arena_dalloc_bin':
src/arena.c:1721:18: warning: variable 'binshard' set but not used [-Wunused-but-set-variable]
 1721 |         unsigned binshard = extent_binshard_get(extent);
      |                  ^~~~~~~~
src/base.c: In function 'base_extent_alloc':
src/base.c:317:31: warning: implicit declaration of function 'base_block_alloc' [-Wimplicit-function-declaration]
  317 |         base_block_t *block = base_block_alloc(tsdn, base, extent_hooks,
      |                               ^~~~~~~~~~~~~~~~
src/base.c:317:31: warning: initialization of 'base_block_t *' {aka 'struct base_block_s *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
src/arena.c: In function 'arena_retain_grow_limit_get_set':
src/base.c: In function 'base_new':
src/base.c:351:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
  351 |         pszind_t pind_last = 0;
      |         ^~~~~~~~
      |         szind_t
src/arena.c:1900:9: error: unknown type name 'pszind_t'; did you mean 'szind_t'?
 1900 |         pszind_t new_ind JEMALLOC_CC_SILENCE_INIT(0);
      |         ^~~~~~~~
      |         szind_t
In file included from include/jemalloc/internal/jemalloc_internal_includes.h:86,
                 from src/base.c:3:
include/jemalloc/internal/extent_inlines.h: In function 'extent_sn_get':
include/jemalloc/internal/extent_inlines.h:86:1: warning: control reaches end of non-void function [-Wreturn-type]
   86 | }
      | ^
src/arena.c:1911:30: warning: implicit declaration of function 'sz_pind2sz'; did you mean 'sz_index2size'? [-Wimplicit-function-declaration]
 1911 |                 *old_limit = sz_pind2sz(arena->retain_grow_limit);
      |                              ^~~~~~~~~~
      |                              sz_index2size
src/jemalloc.c: In function 'malloc_conf_init_helper':
src/jemalloc.c:1233:45: error: type of formal parameter 1 is incomplete
 1233 |                                             bin_shard_sizes, size_start,
      |                                             ^~~~~~~~~~~~~~~
At top level:
src/base.c:144:1: warning: 'base_auto_thp_switch' defined but not used [-Wunused-function]
  144 | base_auto_thp_switch(tsdn_t *tsdn, base_t *base) {
      | ^~~~~~~~~~~~~~~~~~~~
src/base.c:119:1: warning: 'base_extent_init' defined but not used [-Wunused-function]
  119 | base_extent_init(size_t *extent_sn_next, extent_t *extent, void *addr,
      | ^~~~~~~~~~~~~~~~
src/base.c:32:1: warning: 'base_map' defined but not used [-Wunused-function]
   32 | base_map(tsdn_t *tsdn, extent_hooks_t *extent_hooks, unsigned ind, size_t size) {
      | ^~~~~~~~
src/jemalloc.c: In function 'malloc_conf_init':
src/jemalloc.c:1445:39: error: type of formal parameter 2 is incomplete
 1445 |         malloc_conf_init_helper(NULL, NULL, true, opts_cache, buf);
      |                                       ^~~~
src/jemalloc.c:1446:42: error: type of formal parameter 2 is incomplete
 1446 |         malloc_conf_init_helper(sc_data, bin_shard_sizes, false, opts_cache,
      |                                          ^~~~~~~~~~~~~~~
src/jemalloc.c: In function 'malloc_init_hard_a0_locked':
src/jemalloc.c:1496:30: error: type of formal parameter 1 is incomplete
 1496 |         bin_shard_sizes_boot(bin_shard_sizes);
      |                              ^~~~~~~~~~~~~~~
make: *** [src/base.sym.o] Error 1
src/jemalloc.c:1505:36: error: type of formal parameter 2 is incomplete
 1505 |         malloc_conf_init(&sc_data, bin_shard_sizes);
      |                                    ^~~~~~~~~~~~~~~
src/jemalloc.c:1507:28: error: type of formal parameter 2 is incomplete
 1507 |         bin_boot(&sc_data, bin_shard_sizes);
      |                            ^~~~~~~~~~~~~~~
src/jemalloc.c:1495:18: warning: unused variable 'bin_shard_sizes' [-Wunused-variable]
 1495 |         unsigned bin_shard_sizes[SC_NBINS];
      |                  ^~~~~~~~~~~~~~~
In file included from include/jemalloc/internal/jemalloc_internal_includes.h:86,
                 from src/arena.c:3:
include/jemalloc/internal/extent_inlines.h: In function 'extent_nfree_get':
include/jemalloc/internal/extent_inlines.h:123:1: warning: control reaches end of non-void function [-Wreturn-type]
  123 | }
      | ^
include/jemalloc/internal/extent_inlines.h: In function 'extent_sn_get':
include/jemalloc/internal/extent_inlines.h:86:1: warning: control reaches end of non-void function [-Wreturn-type]
   86 | }
      | ^
In file included from include/jemalloc/internal/jemalloc_internal_includes.h:78,
                 from src/arena.c:3:
include/jemalloc/internal/jemalloc_internal_inlines_a.h: In function 'tcache_small_bin_get':
include/jemalloc/internal/jemalloc_internal_inlines_a.h:115:1: warning: control reaches end of non-void function [-Wreturn-type]
  115 | }
      | ^
include/jemalloc/internal/jemalloc_internal_inlines_a.h: In function 'tcache_large_bin_get':
include/jemalloc/internal/jemalloc_internal_inlines_a.h:121:1: warning: control reaches end of non-void function [-Wreturn-type]
  121 | }
      | ^
At top level:
src/arena.c:45:19: warning: 'arena_binind_div_info' defined but not used [-Wunused-variable]
   45 | static div_info_t arena_binind_div_info[SC_NBINS];
      |                   ^~~~~~~~~~~~~~~~~~~~~
make: *** [src/arena.sym.o] Error 1
In file included from include/jemalloc/internal/jemalloc_internal_includes.h:78,
                 from src/jemalloc.c:3:
include/jemalloc/internal/jemalloc_internal_inlines_a.h: In function 'tcache_small_bin_get':
include/jemalloc/internal/jemalloc_internal_inlines_a.h:115:1: warning: control reaches end of non-void function [-Wreturn-type]
  115 | }
      | ^
include/jemalloc/internal/jemalloc_internal_inlines_a.h: In function 'tcache_large_bin_get':
include/jemalloc/internal/jemalloc_internal_inlines_a.h:121:1: warning: control reaches end of non-void function [-Wreturn-type]
  121 | }
      | ^
make: *** [src/jemalloc.sym.o] Error 1
```

**Comment by beckhuang1226** [comment]
I encountered the same error as you.
See if the architecture information of the machine you use to compile this package is included in include/jemalloc/internal/quantum.h

`#  ifdef __loongarch__
#    define LG_QUANTUM         4
#  endif`

Here's the architecture of my machine, I added it and the problem was solved.

**Comment by barracuda156** [comment]
@davidtgoldblatt @Streamlethy Thank you! Fixing a definition worked. I will submit a PR with a correct `ppc` def.
