### ISSUE TITLE
jemalloc can not compile with XCode 11.4 SDK

### ISSUE THREAD

**Issue by vincentdchan** [jemalloc/jemalloc#1801]
I updated my XCode yesterday， now I can not compile jemalloc's master branch.

Error:
```
include/jemalloc/internal/../jemalloc.h:226:28: error: exception specification in declaration does not match previous declaration
    void JEMALLOC_NOTHROW       *je_malloc(size_t size)
                                 ^
include/jemalloc/internal/../jemalloc.h:69:21: note: expanded from macro 'je_malloc'
#  define je_malloc malloc
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/malloc/_malloc.h:40:7: note:
      previous declaration is here
void    *malloc(size_t __size) __result_use_check __alloc_size(1);
         ^
In file included from src/jemalloc_cpp.cpp:9:
In file included from include/jemalloc/internal/jemalloc_preamble.h:21:
```

**Comment by davidtgoldblatt** [comment]
This should be fixed in current DEV head -- patching in 3b4a03b92b2e415415a08f0150fdb9eeb659cd52 should fix things. (If you're getting jemalloc via homebrew, I think that they've already backported the patch).

**Comment by vincentdchan** [comment]
@davidtgoldblatt It's OK now, thank you very much!
