### ISSUE TITLE
Header files not being installed

### ISSUE THREAD

**Issue by spakin** [jemalloc/jemalloc#2489]
My library built atop jemalloc builds fine with 856db56f6ec54f59491fa7897dab9a23d5bf9ff4 but breaks with 41e0b857bef0b787a581c7a8334b46981d5e06ed:

```
/scratch/users/pakin/sicm-ci-test/tmp/include/jemalloc/jemalloc.h:246:10: fatal error: jemalloc/jemalloc_defs.h: No such file or directory
  246 | #include "jemalloc/jemalloc_defs.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

As the compiler error suggests, `jemalloc_defs.h` is nowhere to be found in the installation directory:

```console
$ find /scratch/users/pakin/sicm-ci-test/tmp/ -type f
/scratch/users/pakin/sicm-ci-test/tmp/include/jemalloc/jemalloc.h
/scratch/users/pakin/sicm-ci-test/tmp/share/doc/jemalloc/jemalloc.html
/scratch/users/pakin/sicm-ci-test/tmp/share/man/man3/jemalloc.3
/scratch/users/pakin/sicm-ci-test/tmp/lib/libjemalloc.so.2
/scratch/users/pakin/sicm-ci-test/tmp/lib/libjemalloc.a
/scratch/users/pakin/sicm-ci-test/tmp/lib/pkgconfig/jemalloc.pc
/scratch/users/pakin/sicm-ci-test/tmp/lib/libjemalloc_pic.a
/scratch/users/pakin/sicm-ci-test/tmp/bin/jeprof
/scratch/users/pakin/sicm-ci-test/tmp/bin/jemalloc.sh
/scratch/users/pakin/sicm-ci-test/tmp/bin/jemalloc-config
```

**Comment by interwq** [comment]
Thanks for letting us know @spakin !

cc: @Svetlitski

**Comment by Svetlitski** [comment]
Thank you for reporting this and taking the time to bisect the issue @spakin. This should be fixed by PR #2492.

**Comment by jundaf2** [comment]
Thanks for reporting this, I just encountered this issue and solved by manually copying the headers to the system destination
@spakin @interwq  @Svetlitski. I think maybe the Makefile should be updated

**Comment by spakin** [comment]
@Svetlitski: I confirm the fix works.  Thanks for taking care of that so promptly.

**Comment by interwq** [comment]
@jundaf2 can you try the current dev branch again? #2492 which was just landed should have fixed it.
